FROM golang:1.22-alpine AS build

WORKDIR /app

COPY go.mod go.sum* ./
RUN go mod download

COPY main.go .

RUN CGO_ENABLED=0 GOOS=linux go build -o worker .

FROM scratch

COPY --from=build /app/worker /worker

ENTRYPOINT ["/worker"]